// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qmqydpjsplfvwuuxvdlu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFtcXlkcGpzcGxmdnd1dXh2ZGx1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2OTQxMjgsImV4cCI6MjA1OTI3MDEyOH0.cqdgDIbWCJMQkKxuTJRKHC2HjeagnclOA28OofRvKAs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);